### ISSUE TITLE
seo-extension-blog-error

### ISSUE THREAD

**Issue by daslicht** [anand-patel/oc-seo-extension#23]
Hi, 
when I try to save a blog post I get the following error:

![](http://i.imgur.com/OkLBy5Q.png)

related:
https://octobercms.com/forum/post/seo-extension-blog-error?page=1

**Comment by marcoelho97** [comment]
Do this:
Unistall the blog plugin first, then unistall SEO plugin.
Then, install blog plugin and then SEO.

The reason for this is the SEO plugin messes with the blog database. If you install the blog plugin after installing the SEO plugin, it will bug. That's also why you have to unistall blog first.

**Comment by daslicht** [comment]
Thank you !
