### ISSUE TITLE
SEO Settings Error with Build 349

### ISSUE THREAD

**Issue by marcoelho97** [anand-patel/oc-seo-extension#24]
I have updated from build 318 to 349, and now, in SEO Settings, I'm getting the following error:
"The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 38 (near "path: @/plugins/anandpatel/seoextension/models/settings/_other_tags_hint.htm")." on line 259 of /home/NAMEHERE/public_html/vendor/symfony/yaml/Inline.php
![image](https://cloud.githubusercontent.com/assets/13586621/16911521/dbe1aa32-4cd6-11e6-9920-d8de8fc58541.png)

**Comment by marcoelho97** [comment]
@anand-patel Any news on this matter?

**Comment by raakesh** [comment]
Even I'm facing the same problem.

**Comment by vannut** [comment]
With this PR #22 it should be fixed. Which was just merged by @anand-patel

**Comment by vannut** [comment]
Can you confirm if #22 fixes this?

**Comment by anand-patel** [comment]
@vannut Yes it fixes this issue.

**Comment by anand-patel** [comment]
#22  fixed issue, updated on market place. sorry for little late.
