### ISSUE TITLE
I18N and L10N

### ISSUE THREAD

**Issue by mahony0** [anand-patel/oc-seo-extension#5]
I'm developing E-commerce system with October and using this plugin. If you can add lang folder and make texts and inputs dynamic -takes only 5-10 mins.- this plugin will be very useful for me and others. I can help editing the plugin btw. Thanks.

**Comment by anand-patel** [comment]
I have not updated plugin on market place but on Github it has lang folder, please check. i will update it soon, by the way which language you want to add ?

**Comment by mahony0** [comment]
Sorry, I didn't see lang folder and now I am. I need to use Turkish language. I translated strings into Turkish and now I'm opening a pull request for that. Thanks for this useful plugin. When you need help about plugin, I will help as I can be..
